name: 部署网站

on:
  workflow_run:
    workflows:
      - 部署文档
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages
        
      - name: 同步静态资源到服务器
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.CPGEGE_HOST }}
          username: ${{ secrets.CPGEGE_USERNAME }}
          password: ${{ secrets.CPGEGE_PASSWORD }}
          port: ${{ secrets.CPGEGE_PORT }}
          source: "./,!.git"
          target: ${{ secrets.CPGEGE_REMOTE_TARGET }}

      - name: print
        env:
          host: ${{ secrets.CPGEGE_HOST }}
          username: ${{ secrets.CPGEGE_USERNAME }}
          port: ${{ secrets.CPGEGE_PORT }}
          target: ${{ secrets.CPGEGE_REMOTE_TARGET }}
        run: |
          echo: "host: $host"
          echo: "username: $username"
          echo: "port: $port"
          echo: "target: $target"
